const {chromium} = require('playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
const ids = JSON.parse(fs.readFileSync('/private/tmp/ip-client-review-artifacts/ids.json','utf8'));
const base = 'http://127.0.0.1:18888/index.php/';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1360,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',d=>{errors.push('Unexpected dialog');d.dismiss()});
 await page.goto(base+'sessions/login');
 await page.locator('#email').fill('admin@example.invalid');
 await page.locator('#password').fill(fs.readFileSync(process.env.PROPERTY_TEST_LOGIN_FILE,'utf8'));
 await Promise.all([page.waitForURL('**/dashboard'),page.locator('button[type=submit]').click()]);
 await page.goto(base+'client-updates/view/'+ids.id);
 assert.equal(await page.getByRole('button',{name:'Mark resolved',exact:true}).count(),0);
 await page.screenshot({path:'/private/tmp/ip-client-review-artifacts/new-customer.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:'/private/tmp/ip-client-review-artifacts/mobile.png',fullPage:true});
 if(await page.locator('[name=separate_customer]').count()) await page.locator('[name=separate_customer]').check();
 await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Create customer and resolve',exact:true}).click()]);
 await page.getByRole('heading',{name:'Customer information saved'}).waitFor();
 const customerURL=await page.getByRole('link',{name:'View customer',exact:true}).getAttribute('href');
 const client=Number(customerURL.split('/').pop());assert(client>0);
 await page.getByRole('link',{name:'View customer',exact:true}).click();
 assert((await page.locator('body').innerText()).includes('Review Browser'));
 console.log('PASS: create and resolve, customer link, mobile layout');
 await page.goto(base+'client-updates/view/'+ids.duplicate);
 assert((await page.locator('body').innerText()).includes('Possible matching customers'));
 assert.equal(await page.locator('.cu-review script').count(),0);
 await page.locator('#cu-customer').selectOption(String(client));
 assert(await page.getByRole('button',{name:'Review selection before saving'}).isDisabled());
 await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Review selection',exact:true}).click()]);
 assert.equal(await page.locator('[name="fields[]"]:checked').count(),0);
 await page.locator('[name="fields[]"][value="phone"]').check();
 await page.setViewportSize({width:1360,height:1000});
 await page.screenshot({path:'/private/tmp/ip-client-review-artifacts/existing-customer.png',fullPage:true});
 await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Update customer and resolve'}).click()]);
 await page.getByRole('heading',{name:'Customer information saved'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'View customer',exact:true}).getAttribute('href'),customerURL);
 console.log('PASS: explicit match selection, selective update, escaped submitted text');
 await page.goto(base+'client-updates/view/'+ids.dismiss);
 const token=await page.locator('#cu-apply [name=review_version]').inputValue();
 const form=await page.locator('#cu-apply').evaluate(node=>Object.fromEntries(new FormData(node)));
 const stale=await page.request.post(base+'client-updates/resolve/'+ids.dismiss,{form});
 assert((await stale.text()).includes('Nothing was changed.'));
 // This either fails CSRF or returns to review; never marks it resolved.
 await page.reload(); assert(await page.getByRole('button',{name:'Create customer and resolve'}).isVisible());
 const badCsrf=await page.request.post(base+'client-updates/apply/'+ids.dismiss,{form:{customer_id:'0',review_version:token}});
 assert.equal(badCsrf.status(),403);
 await page.getByText('Dismiss without customer changes',{exact:true}).click();
 await page.locator('#resolution_note').fill('Synthetic duplicate test');
 await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Dismiss without changes',exact:true}).click()]);
 assert((await page.locator('body').innerText()).includes('Dismissed without customer changes: Synthetic duplicate test'));
 assert.equal(await page.getByRole('link',{name:'View customer',exact:true}).count(),0);
 const anon=await browser.newContext();
 const response=await anon.request.post(base+'client-updates/apply/'+ids.dismiss,{form:{customer_id:'0'}});
 assert([200,302,303,403].includes(response.status()));
 assert(!response.url().includes('/clients/view/'));
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: dismissal, CSRF rejection, no browser errors');
 fs.writeFileSync('/private/tmp/ip-client-review-artifacts/browser-result.json',JSON.stringify({client,passed:true}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
