const {chromium}=require('playwright');const fs=require('fs');
const output=process.env.PROPERTY_BROWSER_OUTPUT || '/tmp/ip-browser-test';fs.mkdirSync(output,{recursive:true});
const loginFile=process.env.PROPERTY_TEST_LOGIN_FILE;if(!loginFile)throw new Error('Set PROPERTY_TEST_LOGIN_FILE to the isolated fixture password file');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1400,height:1100}});p.setDefaultTimeout(10000);p.setDefaultNavigationTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:18888/index.php/sessions/login');await p.locator('#email').fill('admin@example.invalid');await p.locator('#password').fill(fs.readFileSync(loginFile,'utf8'));await Promise.all([p.waitForURL('**/dashboard'),p.locator('button[type=submit]').click()]);
console.log('Opening customer');await p.goto('http://127.0.0.1:18888/index.php/clients/view/1');console.log('Customer loaded');if(await p.locator('.property-card').count()!==2)throw Error('Two property cards missing');await p.locator('#client_note').fill('Unsaved note survives property changes');
console.log('Editing property');const card=p.locator('.property-card').first();await card.getByRole('button',{name:'Edit',exact:true}).click();await card.locator('[name="address[label]"]').fill('Main home');let response=p.waitForResponse(r=>r.url().endsWith('/service-properties/client/1/save'));await card.getByRole('button',{name:'Save changes'}).click();let saved=await(await response).json();if(saved.success!==1)throw Error('Inline save failed '+saved.message);await p.waitForFunction(()=>document.querySelector('.property-feedback').textContent.includes('saved'));if(await p.locator('#client_note').inputValue()!=='Unsaved note survives property changes')throw Error('Note draft lost');if(!p.url().endsWith('/clients/view/1'))throw Error('Left customer page');
console.log('Archiving');p.once('dialog',d=>d.accept());response=p.waitForResponse(r=>r.url().endsWith('/service-properties/client/1/status'));await p.locator('.property-card').first().getByRole('button',{name:'Archive',exact:true}).click();if((await(await response).json()).success!==1)throw Error('Archive failed');await p.locator('.property-archived summary').click();response=p.waitForResponse(r=>r.url().endsWith('/service-properties/client/1/status'));await p.getByRole('button',{name:'Restore',exact:true}).first().click();if((await(await response).json()).success!==1)throw Error('Restore failed');
console.log('Testing duplicate');await p.getByRole('button',{name:'Add property',exact:true}).first().click();let form=p.locator('#property-new');for(const[k,v]of Object.entries({address_1:'200 Service Road',city:'Springfield',state:'IL',zip:'62701'}))await form.locator('[name="address['+k+']"]').fill(v);response=p.waitForResponse(r=>r.url().endsWith('/service-properties/client/1/save'));await form.getByRole('button',{name:'Add property',exact:true}).click();if((await(await response).json()).success!==0)throw Error('Duplicate allowed');if(await form.locator('[name="address[city]"]').inputValue()!=='Springfield')throw Error('Validation lost fields');await form.getByRole('button',{name:'Cancel',exact:true}).click();
console.log('Testing notes');const note='Readable customer note '+Date.now()+'\nSecond line\nThird line\nFourth line\nFifth line';await p.locator('#client_note').fill(note);await p.getByRole('button',{name:'Add note',exact:true}).click();await p.waitForFunction(t=>document.querySelector('#notes_list').textContent.includes(t),note.split('\n')[0]);const np=p.locator('#notes_list .panel').filter({hasText:note.split('\n')[0]});await np.getByRole('button',{name:'Show full note',exact:true}).click();if(await np.locator('.customer-note-preview').count())throw Error('Note expand failed');await np.getByRole('button',{name:'Show less',exact:true}).click();
console.log('Testing tabs');for(const tab of ['Invoices','Quotes','Payments','Overview']){await p.locator('.customer-nav').getByRole('link',{name:tab,exact:true}).click();}
console.log('Testing create modals');await p.locator('.client-create-invoice').click();await p.waitForSelector('#modal-placeholder .modal',{state:'visible'});await p.locator('#modal-placeholder .modal [data-dismiss=modal]').first().click();await p.waitForSelector('#modal-placeholder .modal',{state:'hidden'});await p.locator('.client-create-quote').click();await p.waitForSelector('#modal-placeholder .modal',{state:'visible'});await p.locator('#modal-placeholder .modal [data-dismiss=modal]').first().click();await p.waitForSelector('#modal-placeholder .modal',{state:'hidden'});
await p.screenshot({path:output+'/customer-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:output+'/customer-mobile.png',fullPage:true});if(await p.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Mobile overflow');await p.goto('http://127.0.0.1:18888/index.php/clients/view/2');await p.locator('#customer-properties').getByRole('button',{name:'Add property',exact:true}).first().click();const nf=p.locator('#property-new');const street=Date.now()+' Customer Test Lane';for(const[k,v]of Object.entries({address_1:street,city:'Springfield',state:'IL',zip:'62701'}))await nf.locator('[name="address['+k+']"]').fill(v);response=p.waitForResponse(r=>r.url().endsWith('/service-properties/client/2/save'));await nf.getByRole('button',{name:'Add property',exact:true}).click();if((await(await response).json()).success!==1)throw Error('Inline add failed');await p.waitForFunction(t=>document.querySelector('.property-cards').textContent.includes(t),street);if(errors.length)throw Error(errors.join(';'));console.log('Customer layout, inline save/archive/restore, draft preservation, duplicate validation, notes, history tabs, create modals and mobile checks passed.');await b.close();})().catch(e=>{console.error(e.message);process.exit(1)});
