// Requires the isolated property integration fixtures, more than 50 active customers,
// and tests/fixtures/customer-directory.sql. Never seed or run against production.
const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
const output=process.env.PROPERTY_BROWSER_OUTPUT||'/tmp/ip-browser-test';fs.mkdirSync(output,{recursive:true});
const loginFile=process.env.PROPERTY_TEST_LOGIN_FILE;if(!loginFile)throw Error('Set PROPERTY_TEST_LOGIN_FILE');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1400,height:1000}});p.setDefaultTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
const base='http://127.0.0.1:18888/index.php/';
await p.goto(base+'sessions/login');await p.locator('#email').fill('admin@example.invalid');await p.locator('#password').fill(fs.readFileSync(loginFile,'utf8'));await Promise.all([p.waitForURL('**/dashboard'),p.locator('button[type=submit]').click()]);
await p.goto(base+'clients/status/active');assert.equal(await p.locator('[data-customer-id]').count(),25);assert.equal(await p.locator('.directory-summary').count(),2);assert.match(await p.locator('.directory-summary').first().innerText(),/Showing 1–25 of/);
await p.screenshot({path:output+'/list-desktop.png',fullPage:true});
const firstIds=await p.locator('[data-customer-id]').evaluateAll(es=>es.map(e=>e.dataset.customerId));await p.locator('.directory-page-controls').first().getByRole('link',{name:'Next',exact:true}).click();assert.match(await p.locator('.directory-summary').first().innerText(),/Showing 26–50 of/);const secondIds=await p.locator('[data-customer-id]').evaluateAll(es=>es.map(e=>e.dataset.customerId));assert(!secondIds.some(x=>firstIds.includes(x)));
const offPageName=await p.locator('.directory-name').first().innerText();await p.locator('#customer-search').fill(offPageName);await p.getByRole('button',{name:'Search',exact:true}).click();assert((await p.locator('.directory-name').allTextContents()).includes(offPageName));assert.match(await p.locator('.directory-summary').first().innerText(),/Showing 1–/);
await p.goto(base+'clients/status/active?q=Sample%20200%20Service%20Road');assert(await p.locator('[data-customer-id="1"]').count());
await p.goto(base+'clients/status/active?q=ZZZNoSuchCustomer98765');assert.equal(await p.locator('[data-customer-id]').count(),0);assert.match(await p.locator('.directory-empty').innerText(),/No customers found/);assert.match(await p.locator('.directory-summary').first().innerText(),/Showing 0–0 of 0/);await p.getByRole('link',{name:'Clear search'}).click();assert.equal(await p.locator('[data-customer-id]').count(),25);
await p.locator('#customer-page-size').selectOption('50');await p.waitForURL('**per_page=50');assert.equal(await p.locator('[data-customer-id]').count(),50);
await p.goto(base+'clients/status/active/999999?per_page=25');assert(!(await p.locator('.directory-page-controls').first().getByRole('link',{name:'Next',exact:true}).count()));assert(await p.locator('[data-customer-id]').count()>0);
await p.goto(base+'clients/status/active?q=%25');assert.equal(await p.locator('[data-customer-id]').count(),0);
await p.goto(base+'clients/status/active?q=%3Cscript%3Ealert(1)%3C%2Fscript%3E');assert.equal(await p.locator('#customer-search').inputValue(),'<script>alert(1)</script>');assert.equal(await p.locator('[data-customer-id]').count(),0);
await p.goto(base+'clients/status/active?q[]=bad&per_page[]=bad');assert.equal(await p.locator('[data-customer-id]').count(),25);
await p.goto(base+'clients/status/active?q=Directory%20Fixture');assert.equal(await p.locator('[data-customer-id]').count(),1);await p.locator('.directory-filters').getByRole('link',{name:/Inactive/}).click();assert.equal(await p.locator('[data-customer-id]').count(),1);assert.match(await p.locator('.directory-status').innerText(),/Inactive/);await p.locator('.directory-filters').getByRole('link',{name:/All/}).click();assert.equal(await p.locator('[data-customer-id]').count(),2);
await p.goto(base+'clients/status/active?q=2025550143');assert.equal(await p.locator('[data-customer-id]').count(),1);assert.match(await p.locator('.directory-contact').innerText(),/\(202\) 555-0143/);
await p.goto(base+'clients/status/active?q=Directory%20Fixture');await p.locator('.directory-actions').getByRole('button',{name:/More actions/}).click();await p.locator('.client-create-invoice').click();await p.waitForSelector('#modal-placeholder .modal',{state:'visible'});await p.locator('#modal-placeholder .modal [data-dismiss=modal]').first().click();await p.waitForSelector('#modal-placeholder .modal',{state:'hidden'});
await p.locator('.directory-actions').getByRole('button',{name:/More actions/}).click();await p.locator('.client-create-quote').click();await p.waitForSelector('#modal-placeholder .modal',{state:'visible'});await p.locator('#modal-placeholder .modal [data-dismiss=modal]').first().click();await p.waitForSelector('#modal-placeholder .modal',{state:'hidden'});
await p.locator('.directory-actions').getByRole('link',{name:/Edit/}).click();assert.match(p.url(),/clients\/form\//);await p.goBack();await p.locator('.directory-actions').getByRole('link',{name:/View/}).click();assert.match(p.url(),/clients\/view\//);
await p.goto(base+'clients/status/active');await p.setViewportSize({width:390,height:844});await p.screenshot({path:output+'/list-mobile.png',fullPage:false});assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)));await p.locator('.directory-page-controls').first().getByRole('link',{name:'Next',exact:true}).click();assert.match(await p.locator('.directory-summary').first().innerText(),/Showing 26–50/);assert.deepEqual(errors,[]);console.log('PASS: counts, paging, search across pages/properties, status scope, phone formatting, empty results, escaping, invalid inputs, actions and mobile layout');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
