const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
const output=process.env.PROPERTY_BROWSER_OUTPUT||'/tmp/ip-browser-test';fs.mkdirSync(output,{recursive:true});
const loginFile=process.env.PROPERTY_TEST_LOGIN_FILE;if(!loginFile)throw Error('Set PROPERTY_TEST_LOGIN_FILE');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1400,height:1100}});p.setDefaultTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:18888/index.php/';
await p.goto(base+'sessions/login');await p.locator('#email').fill('admin@example.invalid');await p.locator('#password').fill(fs.readFileSync(loginFile,'utf8'));await Promise.all([p.waitForURL('**/dashboard'),p.locator('button[type=submit]').click()]);
assert.equal(await p.locator('.dash-table tbody tr').count(),5);assert.match(await p.locator('[data-dashboard="unpaid"]').innerText(),/Excludes unsent drafts/);assert.match(await p.locator('[data-dashboard="receipts"]').innerText(),/recorded payment dates/);assert.match(await p.locator('.dash-foot').first().innerText(),/Showing the latest 5 of/);
await p.screenshot({path:output+'/dashboard-desktop.png',fullPage:true});
await p.locator('#dashboard-customer-search').fill('Sample');await p.getByRole('button',{name:'Search customers',exact:true}).click();assert.match(p.url(),/clients\/status\/active\?q=Sample/);assert.match(await p.locator('.directory-name').first().innerText(),/Sample/);await p.goto(base+'dashboard');
for(const name of ['Create invoice','Create quote']){await p.locator('.dash-actions').getByRole('link',{name:new RegExp(name)}).click();await p.waitForSelector('#modal-placeholder .modal',{state:'visible'});await p.locator('#modal-placeholder .modal [data-dismiss=modal]').first().click();await p.waitForSelector('#modal-placeholder .modal',{state:'hidden'});}
for(const [name,path]of [['Record payment','payments/form'],['Add customer','clients/form']]){await p.locator('.dash-actions').getByRole('link',{name:new RegExp(name)}).click();assert(p.url().includes(path));await p.goto(base+'dashboard');}
await p.getByRole('link',{name:'View unpaid invoices',exact:true}).click();assert(p.url().endsWith('invoices/status/unpaid'));assert(await p.locator('.index-options a.btn-primary').filter({hasText:'Unpaid'}).count());const filtered=p.waitForResponse(r=>r.url().includes('filter/ajax/filter_invoices'));await p.locator('#filter').fill('NoSuchDashboardInvoiceXYZ');await p.locator('#filter').press('x');await filtered;assert.equal(await p.locator('#filter_results tbody tr .label').count(),0);await p.goto(base+'dashboard');
await p.getByRole('link',{name:'Review overdue invoices',exact:true}).click();assert(p.url().endsWith('invoices/status/overdue'));await p.goto(base+'dashboard');await p.getByRole('link',{name:'Review drafts',exact:true}).click();assert(p.url().endsWith('invoices/status/draft'));await p.goto(base+'dashboard');
for(const detail of await p.locator('.dash-more').all()){assert.equal(await detail.getAttribute('open'),null);await detail.locator('summary').click();assert.notEqual(await detail.getAttribute('open'),null);await detail.locator('summary').click();}
await p.setViewportSize({width:390,height:844});await p.locator('.dash-intro').scrollIntoViewIfNeeded();await p.screenshot({path:output+'/dashboard-mobile.png',fullPage:false});assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)));assert(await p.locator('.dash-actions').getByRole('link',{name:/Record payment/}).isVisible());assert.deepEqual(errors,[]);console.log('PASS: dashboard layout, recent limits, customer search, creation dialogs, invoice filters, actions, expandable sections and mobile');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
