CREATE TABLE IF NOT EXISTS `ip_client_update_requests` (
    `request_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `request_reference` VARCHAR(20) NOT NULL,
    `full_name` VARCHAR(150) NOT NULL,
    `service_address_1` VARCHAR(150) NOT NULL,
    `service_address_2` VARCHAR(150) DEFAULT NULL,
    `service_city` VARCHAR(100) NOT NULL,
    `service_state` VARCHAR(100) NOT NULL,
    `service_zip` VARCHAR(20) NOT NULL,
    `additional_service_addresses` LONGTEXT DEFAULT NULL,
    `mailing_same_as_service` TINYINT(1) NOT NULL DEFAULT 1,
    `mailing_address_1` VARCHAR(150) DEFAULT NULL,
    `mailing_address_2` VARCHAR(150) DEFAULT NULL,
    `mailing_city` VARCHAR(100) DEFAULT NULL,
    `mailing_state` VARCHAR(100) DEFAULT NULL,
    `mailing_zip` VARCHAR(20) DEFAULT NULL,
    `phone` VARCHAR(30) NOT NULL,
    `email` VARCHAR(254) NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `resolution_note` TEXT DEFAULT NULL,
    `applied_client_id` INT DEFAULT NULL,
    `applied_at` DATETIME DEFAULT NULL,
    `applied_by` INT DEFAULT NULL,
    `submitted_at` DATETIME NOT NULL,
    `resolved_at` DATETIME DEFAULT NULL,
    `resolved_by` INT DEFAULT NULL,
    PRIMARY KEY (`request_id`),
    UNIQUE KEY `request_reference` (`request_reference`),
    KEY `status_submitted_at` (`status`, `submitted_at`),
    KEY `resolved_at` (`resolved_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
