<?php
$line_id = $item ? (int)$item->item_id : 0;
$prefix = 'charge-' . $line_id . '-';
$pid = (int)($item->item_service_property_id ?? 0);
$details_open = $item && ($item->item_product_unit_id || (float)$item->item_discount_amount || $item->item_tax_rate_id || ($invoice->invoice_is_recurring && (string)$item->item_is_recurring === '0'));
?>
<article class="iw-charge<?php echo $item ? ' item' : ''; ?>" data-order="<?php echo (int)($item->item_order ?? 0); ?>" data-address="<?php echo html_escape($item->item_service_address ?? ''); ?>">
<?php foreach (['invoice_id' => $invoice_id, 'item_id' => $line_id ?: '', 'item_product_id' => $item->item_product_id ?? '', 'item_task_id' => $item->item_task_id ?? ''] as $field => $value) { ?><input type="hidden" name="<?php echo $field; ?>" class="<?php echo $field === 'item_task_id' ? 'item-task-id' : ''; ?>" value="<?php echo html_escape($value); ?>"><?php } ?>
<div class="iw-charge-fields"><label for="<?php echo $prefix; ?>name"><?php echo $w('service'); ?><input id="<?php echo $prefix; ?>name" name="item_name" class="form-control" value="<?php echo html_escape($item->item_name ?? ''); ?>"<?php echo $disabled; ?>></label>
<label for="<?php echo $prefix; ?>quantity"><?php _trans('quantity'); ?><input id="<?php echo $prefix; ?>quantity" name="item_quantity" class="form-control" inputmode="decimal" value="<?php echo $item ? format_quantity($item->item_quantity) : ''; ?>"<?php echo $disabled; ?>></label>
<label for="<?php echo $prefix; ?>price"><?php echo $w('rate'); ?> (<?php echo html_escape(get_setting('currency_symbol')); ?>)<input id="<?php echo $prefix; ?>price" name="item_price" class="form-control" inputmode="decimal" value="<?php echo $item ? format_amount($item->item_price) : ''; ?>"<?php echo $disabled; ?>></label></div>
<label for="<?php echo $prefix; ?>description"><?php _trans('description'); ?><textarea id="<?php echo $prefix; ?>description" name="item_description" class="form-control" rows="2"<?php echo $disabled; ?>><?php echo html_escape($item->item_description ?? ''); ?></textarea></label>
<details class="iw-charge-details"<?php echo $details_open ? ' open' : ''; ?>><summary><?php echo $w('charge_details'); ?></summary><div class="iw-detail-fields">
<label for="<?php echo $prefix; ?>unit"><?php _trans('product_unit'); ?><select id="<?php echo $prefix; ?>unit" name="item_product_unit_id" class="form-control"<?php echo $disabled; ?>><option value="0"><?php _trans('none'); ?></option><?php foreach ($units as $unit) { ?><option value="<?php echo (int)$unit->unit_id; ?>"<?php echo (int)($item->item_product_unit_id ?? 0) === (int)$unit->unit_id ? ' selected' : ''; ?>><?php echo html_escape($unit->unit_name . '/' . $unit->unit_name_plrl); ?></option><?php } ?></select></label>
<label for="<?php echo $prefix; ?>tax"><?php _trans('tax_rate'); ?><select id="<?php echo $prefix; ?>tax" name="item_tax_rate_id" class="form-control"<?php echo $disabled; ?>><option value="0"><?php _trans('none'); ?></option><?php foreach ($tax_rates as $rate) { ?><option value="<?php echo (int)$rate->tax_rate_id; ?>"<?php echo (int)($item->item_tax_rate_id ?? get_setting('default_item_tax_rate')) === (int)$rate->tax_rate_id ? ' selected' : ''; ?>><?php echo html_escape($rate->tax_rate_name) . ' (' . format_amount($rate->tax_rate_percent) . '%)'; ?></option><?php } ?></select></label>
<label for="<?php echo $prefix; ?>discount"><?php _trans('discount'); ?> (<?php echo html_escape(get_setting('currency_symbol') . ' ' . trans('per_item')); ?>)<input id="<?php echo $prefix; ?>discount" name="item_discount_amount" class="form-control" inputmode="decimal" value="<?php echo $item ? format_amount($item->item_discount_amount) : ''; ?>"<?php echo $disabled; ?>></label>
<?php if ($invoice->invoice_is_recurring) { ?><label for="<?php echo $prefix; ?>recurring"><?php _trans('recurring'); ?><select id="<?php echo $prefix; ?>recurring" name="item_is_recurring" class="form-control"<?php echo $disabled; ?>><option value="1"><?php _trans('yes'); ?></option><option value="0"<?php echo $item && (string)$item->item_is_recurring === '0' ? ' selected' : ''; ?>><?php _trans('no'); ?></option></select></label><?php } ?>
</div></details>
<div class="iw-row-actions">
<?php if ($can_add) { ?><details class="iw-row-more"><summary><?php echo $w('row_actions'); ?></summary><div class="iw-actions"><button type="button" class="btn btn-default iw-up"><?php _trans('move_up'); ?></button><button type="button" class="btn btn-default iw-down"><?php _trans('move_down'); ?></button><button type="button" class="btn btn-link iw-remove"><?php echo $w('remove'); ?></button></div>
<?php if ($state) { ?><label for="<?php echo $prefix; ?>property"><?php echo $w('change_property'); ?><select id="<?php echo $prefix; ?>property" name="item_service_property_id" class="form-control"><option value=""><?php echo $w('choose_property'); ?></option><?php foreach ($properties as $property) { if (!$property['active'] && (int)$property['property_id'] !== $pid) continue; ?><option value="<?php echo (int)$property['property_id']; ?>"<?php echo (int)$property['property_id'] === $pid ? ' selected' : ''; ?>><?php echo html_escape(Property_rules::text($property) . (!$property['active'] ? ' (' . trans('invoice_workspace_archived') . ')' : '')); ?></option><?php } ?></select></label><?php } ?>
</details><?php } elseif ($state) { ?><input type="hidden" name="item_service_property_id" value="<?php echo $pid ?: ''; ?>"><?php } ?>
<span class="iw-saved-line"><?php echo $w('saved_total'); ?>: <?php echo $item ? format_currency($item->item_total) : '&mdash;'; ?></span>
</div></article>
