<details class="iw-card iw-extra" id="invoice-settings"><summary><?php echo $w('additional'); ?></summary>
<?php if ($editing) { ?><div class="iw-detail-fields">
<label for="invoice_number"><?php _trans('invoice'); ?> #<input id="invoice_number" class="form-control" value="<?php echo html_escape($invoice->invoice_number); ?>"<?php echo $disabled; ?>></label>
<label for="invoice_status_id"><?php _trans('status'); ?><select id="invoice_status_id" class="form-control"><?php foreach ($invoice_statuses as $id => $status) { ?><option value="<?php echo (int)$id; ?>"<?php echo (int)$id === (int)$invoice->invoice_status_id ? ' selected' : ''; ?>><?php echo html_escape($status['label']); ?></option><?php } ?></select></label>
<label for="payment_method"><?php _trans('payment_method'); ?><select id="payment_method" class="form-control"><option value="0"><?php _trans('none'); ?></option><?php foreach ($payment_methods as $method) { ?><option value="<?php echo (int)$method->payment_method_id; ?>"<?php echo (int)$method->payment_method_id === (int)$invoice->payment_method ? ' selected' : ''; ?>><?php echo html_escape($method->payment_method_name); ?></option><?php } ?></select></label>
<label for="invoice_password"><?php _trans('invoice_password'); ?><input type="password" autocomplete="new-password" id="invoice_password" class="form-control" value="<?php echo html_escape($invoice->invoice_password); ?>"<?php echo $disabled; ?>></label>
</div>
<details class="iw-charge-details"<?php echo (float)$invoice->invoice_discount_amount || (float)$invoice->invoice_discount_percent ? ' open' : ''; ?>><summary><?php _trans('global_discount'); ?></summary><div class="iw-detail-fields">
<label for="invoice_discount_amount"><?php _trans('discount'); ?> (<?php echo html_escape(get_setting('currency_symbol')); ?>)<input id="invoice_discount_amount" class="form-control" inputmode="decimal" value="<?php echo (float)$invoice->invoice_discount_amount ? format_amount($invoice->invoice_discount_amount) : ''; ?>"<?php echo $disabled; ?>></label>
<label for="invoice_discount_percent"><?php _trans('discount'); ?> (%)<input id="invoice_discount_percent" class="form-control" inputmode="decimal" value="<?php echo (float)$invoice->invoice_discount_percent ? format_amount($invoice->invoice_discount_percent) : ''; ?>"<?php echo $disabled; ?>></label></div></details>
<?php if ($state && !$property_frozen && !$read_only) { ?><label class="iw-check"><input type="checkbox" id="property-refresh"> <?php echo $w('refresh'); ?></label><?php } ?>
<?php } else { ?><dl class="iw-settings-data"><dt><?php _trans('invoice'); ?> #</dt><dd><?php echo html_escape($invoice->invoice_number); ?></dd><dt><?php _trans('status'); ?></dt><dd><?php echo html_escape($invoice_statuses[$invoice->invoice_status_id]['label']); ?></dd><dt><?php _trans('invoicing'); ?></dt><dd><?php echo html_escape(format_user($invoice->user_id)); ?></dd></dl>
<?php if ($change_user && (int)$invoice->invoice_status_id === 1 && !$invoice->creditinvoice_parent_id && !$read_only) { ?><button type="button" class="btn btn-default" id="invoice_change_user"><?php _trans('change_user'); ?></button><?php } ?>
<?php if ($einvoice->name) { ?><p>e-<?php _trans('invoice'); ?>: <?php echo html_escape($einvoice->name); ?><?php if (!$einvoice->user) { ?> &mdash; <a href="<?php echo site_url('users/form/' . (int)$invoice->user_id); ?>"><?php _trans('einvoicing_user_fields_error'); ?></a><?php } ?></p><?php } ?>
<?php if ($legacy_calculation && $invoice_tax_rates) { ?><h4><?php _trans('invoice_tax'); ?></h4><?php foreach ($invoice_tax_rates as $tax) { ?><div class="iw-tax-row"><span><?php echo html_escape($tax->invoice_tax_rate_name) . ' ' . format_amount($tax->invoice_tax_rate_percent) . '% &mdash; ' . format_currency($tax->invoice_tax_rate_amount); ?></span><?php if (!$read_only) { ?><form method="post" action="<?php echo site_url('invoices/delete_invoice_tax/' . (int)$invoice_id . '/' . (int)$tax->invoice_tax_rate_id); ?>"><?php _csrf_field(); ?><button class="btn btn-link iw-remove-tax" type="submit"><?php echo $w('remove'); ?></button></form><?php } ?></div><?php } } ?>
<?php } ?>
<?php if ($custom_fields) { ?><h4><?php _trans('custom_fields'); ?></h4><fieldset<?php echo !$editing || $read_only ? ' disabled' : ''; ?>><?php foreach ($custom_fields as $field) print_field($this->mdl_invoices, $field, $custom_values); ?></fieldset><?php } ?>
</details>
