FROM php:8.3-apache
RUN apt-get update && apt-get install -y --no-install-recommends libpng-dev libonig-dev libxml2-dev libzip-dev unzip git && docker-php-ext-install mysqli pdo_mysql mbstring gd zip && a2enmod rewrite && rm -rf /var/lib/apt/lists/*
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer
WORKDIR /var/www/html

RUN docker-php-ext-install bcmath
